server.port=8081
spring.mongodb.uri=mongodb://localhost/blog
spring.mongodb.ssl.enabled=false

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=user-topic